server:
  port: 8081
  servlet:
    context-path: /oms

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  datasource:
    url: jdbc:mysql://localhost:3306/oms
    username: root
    password: mysql070711
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true

    listener:
      ack-mode: manual

# Custom Kafka Topics Configuration
kafka:
  topics:
    inventory-check-request: inventory-check-request
    inventory-check-response: inventory-check-response
    order-events: order-events
    inventory-events: inventory-events

logging:
  level:
    org.springframework.kafka: DEBUG
    com.oms.service: DEBUG
    org.springframework.kafka.support.serializer: TRACE